<a href="https://colab.research.google.com/github/SGhuman123/Data-Science-Portfolio/blob/main/Udemy_PyTorch_for_Deep_Learning_Bootcamp/Section%200%3A%20PyTorch%20Fundamentals/00_exercises_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
# Create a random tensor of size (7, 7)
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.2228, 0.6276, 0.8527, 0.1115, 0.1318, 0.3922, 0.2841],
        [0.3292, 0.6416, 0.0853, 0.6372, 0.4149, 0.9916, 0.5678],
        [0.5103, 0.7519, 0.3789, 0.4874, 0.3387, 0.8887, 0.4975],
        [0.9231, 0.0542, 0.4194, 0.9110, 0.6126, 0.9549, 0.3583],
        [0.0740, 0.6880, 0.6099, 0.2597, 0.2933, 0.3988, 0.7021],
        [0.8691, 0.6410, 0.8298, 0.1158, 0.6663, 0.2822, 0.0431],
        [0.7253, 0.6663, 0.8270, 0.1296, 0.5039, 0.1648, 0.5347]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_1 = torch.rand(1, 7)
print(random_tensor_1)

# Perform matrix multiplication
result = torch.matmul(random_tensor_1, random_tensor)
print(result)

tensor([[0.0794, 0.5138, 0.9412, 0.8408, 0.4729, 0.6721, 0.5982]])
tensor([[2.4963, 2.2875, 2.1615, 1.8392, 1.9454, 2.6569, 1.7647]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED=0 # try changing this to different values and see what happens to the numbers below

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(1, 7)
random_tensor_D = torch.rand(7, 7)


# Matrix multiply tensors
result = torch.matmul(random_tensor_C, random_tensor_D)
print(result)

tensor([[1.3927, 1.1957, 1.8298, 1.6661, 1.4186, 1.4219, 0.9826]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.manual_seed(seed=RANDOM_SEED) # Use NVIDIA GPU (if available)
else:
    None


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED=0 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)

# Check for access to GPU
import torch
torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_E = torch.rand(2, 3)
random_tensor_F = torch.rand(2, 3)
random_tensor_E, random_tensor_F

(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]]),
 tensor([[0.4901, 0.8964, 0.4556],
         [0.6323, 0.3489, 0.4017]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(random_tensor_E, random_tensor_F.T)
print(result)

tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
# Create a tensor
x = torch.arange(1, 100, 7)
x, x.dtype

x.max(), x.min(), x

(tensor(99),
 tensor(1),
 tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99]))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
x = torch.arange(1, 100, 7)
x, x.dtype

x.argmax(), x.argmin()

(tensor(14), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor
x = torch.rand(2, 3)
x_reshaped = x.reshape(2, 3, 1)


# Print out tensors and their shapes
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
# Remove single dimensions
x_squeezed = x.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[0.2081],
         [0.9298],
         [0.7231]],

        [[0.7423],
         [0.5263],
         [0.2437]]])
Previous shape: torch.Size([2, 3, 1])

New tensor: tensor([[0.2081, 0.9298, 0.7231],
        [0.7423, 0.5263, 0.2437]])
New shape: torch.Size([2, 3])
